apiVersion: binding.operators.coreos.com/v1alpha1
kind: ServiceBinding
metadata:
  name: demo-sb-standalone
spec:
  services:
    - group: redis.redis.opstreelabs.in
      version: v1beta1
      kind: Redis
      name: redis-standalone
  application:
    name: tomcat-deploy
    group: apps
    version: v1
    resource: deployments